 

// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `repo`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=161.9.143.102;Database=SanalPos_Test;User Id=U_sanalpos;password=**zapped**;Application Name='SANALPOS'`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`


 // <auto-generated />
using System;
using System.Collections.Generic;
using System.Configuration; 
using System.Data.Common;
using System.Data;
namespace Prj.COMMON.Enums
{
    public class siltireileberaber_AppEnums
    {
		
public enum Odeme_Yontem 
		{   
			Empty = 0, 
		   	Kredi_Karti = 1010001,
			Google_pay = 1010002,
			HavaleEft = 1010003,
			BKM_ekspress = 1010004,
			Amerikan_Ekspress = 1010005
		}
		public enum Odeme_Yontem_Guvenlik 
		{   
			Empty = 0, 
		   	_2D_guvenlik = 1020001,
			_3D_guvenlik = 1020002
		}
		public enum Odeme_Durum 
		{   
			Empty = 0, 
		   	Key_Olusturuldu = 1030001,
			Odeme_Icin_Bekleniyor = 1030002,
			Istek_Bankaya_Gonderildi = 1030003,
			Odeme_Basarili = 1030004,
			Odeme_Basarisiz = 1030005,
			Odeme_Key_Suresi_Doldu = 1030006
		}
		public enum Araci_Kurum 
		{   
			Empty = 0, 
		   	Halk_Bank = 1040001,
			Ziraat_Bank = 1040002
		}
		
		public enum KodTipList
		{    
			Odeme_Yontem = 101,		
					Odeme_Yontem_Guvenlik = 102,		
					Odeme_Durum = 103,		
					Araci_Kurum = 104		
		} 
	}
}