



// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `repo`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `Server=94.73.147.166;Port=3306;Database=u1555990_BorsaV2;User ID=u1555990_Uborsa;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `MySqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{
}

#pragma warning restore 1591

