// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{


    //[Dapper.Contrib.Extensions.Table("u1555990_borsav2.t_admin_komutlar")] --ae değişiklik
	[Dapper.Contrib.Extensions.Table("t_admin_komutlar")]

    //public partial class T_u1555990_borsav2_t_admin_komutlar --ae değişiklik
	 public partial class t_admin_komutlar    {
		//public T_u1555990_borsav2_t_admin_komutlar()--ae değişiklik
		public t_admin_komutlar()
		{
		}

        //public static string SchemeName { get { return "u1555990_borsav2"; } }
        public static string GetSchema() { return "u1555990_borsav2"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        [Required]
        public int YONTEM_TIP_KOD_ID { get; set;}
        [Required]
        public int IS_SYMBOL_ARAMAYI_HERZAMAN_INDKT { get; set;}
        [Required]
        public int IS_SYMBOL_ARAMAYI_DURDUR { get; set;}
        [Required]
        public int IS_TUM_ALINMISLARI_SAT { get; set;}
        [Required]
        public int IS_TUM_ALIM_PROCESS_KAPAT { get; set;}
        [Required]
        public int IS_SATILMAMISLARIN_PROCSS_AC { get; set;}
        [Required]
        public int IS_DOWN_UP_COINLERE_IZIN_VER { get; set;}
        [Required]
        public int IS_NORMAL_COINLERE_IZIN_VER { get; set;}
        [Required]
        public int IS_KAPAMA_VE_SATSTA_DOWN_UP_GEC { get; set;}
        [Required]
        public int IS_PIYASA_OTO_ISLEM_YAPILBLR { get; set;}
        [Required]
        public int IS_OTOMATIK_ISLEM_YAPILDI { get; set;}
        public DateTime? IS_SON_OTO_ISLEM_YAPLD_TARIH { get; set;}
        public DateTime? SON_KRITIK_UYARI_TARIH { get; set;}
        public int? RAPORL_KRITIK_PIYSA_UYRI_SYISI { get; set;}
        [Required]
        public int ISDELETED { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
    }
	
    
   // public class T_u1555990_borsav2_t_admin_komutlarMapper : AutoClassMapper<T_u1555990_borsav2_t_admin_komutlar> --ae değişiklik
	public class t_admin_komutlarMapper : AutoClassMapper<t_admin_komutlar>
    {
        //public T_u1555990_borsav2_t_admin_komutlarMapper() --ae değişiklik
		public t_admin_komutlarMapper()
            : base()
        {
            Schema("u1555990_borsav2");
        }
    }
 
	//public enum T_u1555990_borsav2_t_admin_komutlar_Properties {--ae değişiklik
	public enum t_admin_komutlar_Properties {

		ID,
		YONTEM_TIP_KOD_ID,
		IS_SYMBOL_ARAMAYI_HERZAMAN_INDKT,
		IS_SYMBOL_ARAMAYI_DURDUR,
		IS_TUM_ALINMISLARI_SAT,
		IS_TUM_ALIM_PROCESS_KAPAT,
		IS_SATILMAMISLARIN_PROCSS_AC,
		IS_DOWN_UP_COINLERE_IZIN_VER,
		IS_NORMAL_COINLERE_IZIN_VER,
		IS_KAPAMA_VE_SATSTA_DOWN_UP_GEC,
		IS_PIYASA_OTO_ISLEM_YAPILBLR,
		IS_OTOMATIK_ISLEM_YAPILDI,
		IS_SON_OTO_ISLEM_YAPLD_TARIH,
		SON_KRITIK_UYARI_TARIH,
		RAPORL_KRITIK_PIYSA_UYRI_SYISI,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		
	}	
}

#pragma warning restore 1591
