// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{


    //[Dapper.Contrib.Extensions.Table("u1555990_borsav2.t_block_coin")] --ae değişiklik
	[Dapper.Contrib.Extensions.Table("t_block_coin")]

    //public partial class T_u1555990_borsav2_t_block_coin --ae değişiklik
	 public partial class t_block_coin    {
		//public T_u1555990_borsav2_t_block_coin()--ae değişiklik
		public t_block_coin()
		{
		}

        //public static string SchemeName { get { return "u1555990_borsav2"; } }
        public static string GetSchema() { return "u1555990_borsav2"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        public DateTime? BLOCK_TARIHI { get; set;}
        public DateTime? BLOCK_BITIS_TARIH { get; set;}
        public string SYMBOL { get; set;}
        [Required]
        public long BLOCK_TIP_KOD_ID { get; set;}
        public decimal? BLOCK_ANI_FIYAT { get; set;}
        public string ACIKLAMA { get; set;}
        public string COLUMN2 { get; set;}
        public string COLUMN3 { get; set;}
        public string COLUMN4 { get; set;}
        [Required]
        public int ISDELETED { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
    }
	
    
   // public class T_u1555990_borsav2_t_block_coinMapper : AutoClassMapper<T_u1555990_borsav2_t_block_coin> --ae değişiklik
	public class t_block_coinMapper : AutoClassMapper<t_block_coin>
    {
        //public T_u1555990_borsav2_t_block_coinMapper() --ae değişiklik
		public t_block_coinMapper()
            : base()
        {
            Schema("u1555990_borsav2");
        }
    }
 
	//public enum T_u1555990_borsav2_t_block_coin_Properties {--ae değişiklik
	public enum t_block_coin_Properties {

		ID,
		BLOCK_TARIHI,
		BLOCK_BITIS_TARIH,
		SYMBOL,
		BLOCK_TIP_KOD_ID,
		BLOCK_ANI_FIYAT,
		ACIKLAMA,
		COLUMN2,
		COLUMN3,
		COLUMN4,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		
	}	
}

#pragma warning restore 1591
