// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{


    //[Dapper.Contrib.Extensions.Table("u1555990_borsav2.t_coin_satis")] --ae değişiklik
	[Dapper.Contrib.Extensions.Table("t_coin_satis")]

    //public partial class T_u1555990_borsav2_t_coin_satis --ae değişiklik
	 public partial class t_coin_satis    {
		//public T_u1555990_borsav2_t_coin_satis()--ae değişiklik
		public t_coin_satis()
		{
		}

        //public static string SchemeName { get { return "u1555990_borsav2"; } }
        public static string GetSchema() { return "u1555990_borsav2"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        [Required]
        public long COIN_ALIS_ID { get; set;}
        [Required]
        public long BINANCE_TRADE_ID { get; set;}
        public string SYMBOL { get; set;}
        [Required]
        public long SATIS_SEBEP_KOD_ID { get; set;}
        public DateTime? TARIH_ISTEK { get; set;}
        [Required]
        public decimal ADET_ISTEK { get; set;}
        [Required]
        public decimal TOPLAM_TUTAR_ISTEK { get; set;}
        [Required]
        public decimal FIYAT_ISTEK { get; set;}
        public DateTime? TARIH { get; set;}
        [Required]
        public decimal ADET { get; set;}
        [Required]
        public decimal FIYAT { get; set;}
        [Required]
        public decimal TOPLAM_TUTAR { get; set;}
        [Required]
        public decimal KOMISYON_TUTAR { get; set;}
        public string ACIKLAMA { get; set;}
        public string COLUMN2 { get; set;}
        public string COLUMN3 { get; set;}
        public string COLUMN4 { get; set;}
        [Required]
        public int ISDELETED { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
    }
	
    
   // public class T_u1555990_borsav2_t_coin_satisMapper : AutoClassMapper<T_u1555990_borsav2_t_coin_satis> --ae değişiklik
	public class t_coin_satisMapper : AutoClassMapper<t_coin_satis>
    {
        //public T_u1555990_borsav2_t_coin_satisMapper() --ae değişiklik
		public t_coin_satisMapper()
            : base()
        {
            Schema("u1555990_borsav2");
        }
    }
 
	//public enum T_u1555990_borsav2_t_coin_satis_Properties {--ae değişiklik
	public enum t_coin_satis_Properties {

		ID,
		COIN_ALIS_ID,
		BINANCE_TRADE_ID,
		SYMBOL,
		SATIS_SEBEP_KOD_ID,
		TARIH_ISTEK,
		ADET_ISTEK,
		TOPLAM_TUTAR_ISTEK,
		FIYAT_ISTEK,
		TARIH,
		ADET,
		FIYAT,
		TOPLAM_TUTAR,
		KOMISYON_TUTAR,
		ACIKLAMA,
		COLUMN2,
		COLUMN3,
		COLUMN4,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		
	}	
}

#pragma warning restore 1591
