// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{


    //[Dapper.Contrib.Extensions.Table("u1555990_borsav2.t_common_log")] --ae değişiklik
	[Dapper.Contrib.Extensions.Table("t_common_log")]

    //public partial class T_u1555990_borsav2_t_common_log --ae değişiklik
	 public partial class t_common_log    {
		//public T_u1555990_borsav2_t_common_log()--ae değişiklik
		public t_common_log()
		{
		}

        //public static string SchemeName { get { return "u1555990_borsav2"; } }
        public static string GetSchema() { return "u1555990_borsav2"; }

        public DateTime? DATETIME { get; set;}
        public string THREAD { get; set;}
        public string LOG_LEVEL { get; set;}
        public string LOGGER { get; set;}
        public string USERNAME { get; set;}
        public string MESSAGE { get; set;}
        public string LOCATION { get; set;}
        public string USER_ID { get; set;}
        public string USER_TYPE { get; set;}
        public string USER_NAME { get; set;}
        public string EXCEPTION { get; set;}
        public string PAGE { get; set;}
        public string HOST { get; set;}
        public string IPADDRESS { get; set;}
        public string BROWSER { get; set;}
        public string PLATFORM { get; set;}
        public string DEVICE { get; set;}
    }
	
    
   // public class T_u1555990_borsav2_t_common_logMapper : AutoClassMapper<T_u1555990_borsav2_t_common_log> --ae değişiklik
	public class t_common_logMapper : AutoClassMapper<t_common_log>
    {
        //public T_u1555990_borsav2_t_common_logMapper() --ae değişiklik
		public t_common_logMapper()
            : base()
        {
            Schema("u1555990_borsav2");
        }
    }
 
	//public enum T_u1555990_borsav2_t_common_log_Properties {--ae değişiklik
	public enum t_common_log_Properties {

		DATETIME,
		THREAD,
		LOG_LEVEL,
		LOGGER,
		USERNAME,
		MESSAGE,
		LOCATION,
		USER_ID,
		USER_TYPE,
		USER_NAME,
		EXCEPTION,
		PAGE,
		HOST,
		IPADDRESS,
		BROWSER,
		PLATFORM,
		DEVICE,
		
	}	
}

#pragma warning restore 1591
