// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{


    //[Dapper.Contrib.Extensions.Table("u1555990_borsav2.t_coin_alis")] --ae değişiklik
	[Dapper.Contrib.Extensions.Table("t_coin_alis")]

    //public partial class T_u1555990_borsav2_t_coin_alis --ae değişiklik
	 public partial class t_coin_alis    {
		//public T_u1555990_borsav2_t_coin_alis()--ae değişiklik
		public t_coin_alis()
		{
		}

        //public static string SchemeName { get { return "u1555990_borsav2"; } }
        public static string GetSchema() { return "u1555990_borsav2"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        public string SYMBOL { get; set;}
        [Required]
        public long YONTEM_TIP_KOD_ID { get; set;}
        [Required]
        public int IS_GERCEK_ISLEM { get; set;}
        public DateTime? TARIH_ISTEK { get; set;}
        [Required]
        public decimal ADET_ISTEK { get; set;}
        [Required]
        public decimal TOPLAM_TUTAR_ISTEK { get; set;}
        [Required]
        public decimal FIYAT_ISTEK { get; set;}
        [Required]
        public decimal ZARAR_DURDUR_FIYAT_ISTEK { get; set;}
        [Required]
        public decimal HEDEF_FIYAT_ISTEK { get; set;}
        [Required]
        public long BINANCE_TRADE_ID { get; set;}
        public DateTime? TARIH { get; set;}
        [Required]
        public decimal ADET { get; set;}
        [Required]
        public decimal FIYAT { get; set;}
        [Required]
        public decimal HEDEF_FIYAT_GUNCELLEME_ORAN { get; set;}
        [Required]
        public decimal HEDEF_FIYAT { get; set;}
        [Required]
        public decimal ZARAR_DURDUR_FIYAT_GUNCELLEME_ORAN { get; set;}
        [Required]
        public decimal ZARAR_DURDUR_FIYAT { get; set;}
        public DateTime? SON_GUNCELLEME_TARIH { get; set;}
        [Required]
        public int GUNCELLEME_COUNT { get; set;}
        [Required]
        public int GUNCELLEME_FEDA_BASLANGIC { get; set;}
        [Required]
        public int GUNCELLEME_FEDA_ANLIK { get; set;}
        [Required]
        public int GUNCELLEME_FEDA_ARTIS_BASAMAK { get; set;}
        [Required]
        public int GUNCELLEME_KONTROL_MIN_DEGERI { get; set;}
        [Required]
        public decimal TOPLAM_TUTAR { get; set;}
        [Required]
        public decimal KOMISYON_TUTAR { get; set;}
        public string ACIKLAMA { get; set;}
        [Required]
        public decimal KAR_ZARAR { get; set;}
        public DateTime? ALIM_ANI_MUM_OPEN_TIME { get; set;}
        public DateTime? ALIM_ANI_MUM_BIRONCEKI_OPEN_TIME { get; set;}
        [Required]
        public int ALIM_ANI_MUM_TIP_DAKIKA { get; set;}
        [Required]
        public int SATIS_ISLEM_SAYISI { get; set;}
        [Required]
        public decimal SATILAN_TOPLAM_ADET { get; set;}
        [Required]
        public int IS_SATISI_TAMAMLANDI { get; set;}
        [Required]
        public int MAX_PARCA_SAYISI { get; set;}
        [Required]
        public decimal PARCA_BASI_ADET_MIKTARI { get; set;}
        [Required]
        public int ISDELETED { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
    }
	
    
   // public class T_u1555990_borsav2_t_coin_alisMapper : AutoClassMapper<T_u1555990_borsav2_t_coin_alis> --ae değişiklik
	public class t_coin_alisMapper : AutoClassMapper<t_coin_alis>
    {
        //public T_u1555990_borsav2_t_coin_alisMapper() --ae değişiklik
		public t_coin_alisMapper()
            : base()
        {
            Schema("u1555990_borsav2");
        }
    }
 
	//public enum T_u1555990_borsav2_t_coin_alis_Properties {--ae değişiklik
	public enum t_coin_alis_Properties {

		ID,
		SYMBOL,
		YONTEM_TIP_KOD_ID,
		IS_GERCEK_ISLEM,
		TARIH_ISTEK,
		ADET_ISTEK,
		TOPLAM_TUTAR_ISTEK,
		FIYAT_ISTEK,
		ZARAR_DURDUR_FIYAT_ISTEK,
		HEDEF_FIYAT_ISTEK,
		BINANCE_TRADE_ID,
		TARIH,
		ADET,
		FIYAT,
		HEDEF_FIYAT_GUNCELLEME_ORAN,
		HEDEF_FIYAT,
		ZARAR_DURDUR_FIYAT_GUNCELLEME_ORAN,
		ZARAR_DURDUR_FIYAT,
		SON_GUNCELLEME_TARIH,
		GUNCELLEME_COUNT,
		GUNCELLEME_FEDA_BASLANGIC,
		GUNCELLEME_FEDA_ANLIK,
		GUNCELLEME_FEDA_ARTIS_BASAMAK,
		GUNCELLEME_KONTROL_MIN_DEGERI,
		TOPLAM_TUTAR,
		KOMISYON_TUTAR,
		ACIKLAMA,
		KAR_ZARAR,
		ALIM_ANI_MUM_OPEN_TIME,
		ALIM_ANI_MUM_BIRONCEKI_OPEN_TIME,
		ALIM_ANI_MUM_TIP_DAKIKA,
		SATIS_ISLEM_SAYISI,
		SATILAN_TOPLAM_ADET,
		IS_SATISI_TAMAMLANDI,
		MAX_PARCA_SAYISI,
		PARCA_BASI_ADET_MIKTARI,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		
	}	
}

#pragma warning restore 1591
