// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{


    //[Dapper.Contrib.Extensions.Table("u1555990_borsav2.t_kod")] --ae değişiklik
	[Dapper.Contrib.Extensions.Table("t_kod")]

    //public partial class T_u1555990_borsav2_t_kod --ae değişiklik
	 public partial class t_kod    {
		//public T_u1555990_borsav2_t_kod()--ae değişiklik
		public t_kod()
		{
		}

        //public static string SchemeName { get { return "u1555990_borsav2"; } }
        public static string GetSchema() { return "u1555990_borsav2"; }

        [Required]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        public long? TIP_ID { get; set;}
        public string KOD { get; set;}
        public int? SIRA { get; set;}
        public string KISA_AD { get; set;}
        public string DIGER_UYG_ENUM_AD { get; set;}
        public int? DIGER_UYG_ID { get; set;}
        public string COLUMN4 { get; set;}
        [Required]
        public int ISDELETED { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
    }
	
    
   // public class T_u1555990_borsav2_t_kodMapper : AutoClassMapper<T_u1555990_borsav2_t_kod> --ae değişiklik
	public class t_kodMapper : AutoClassMapper<t_kod>
    {
        //public T_u1555990_borsav2_t_kodMapper() --ae değişiklik
		public t_kodMapper()
            : base()
        {
            Schema("u1555990_borsav2");
        }
    }
 
	//public enum T_u1555990_borsav2_t_kod_Properties {--ae değişiklik
	public enum t_kod_Properties {

		ID,
		TIP_ID,
		KOD,
		SIRA,
		KISA_AD,
		DIGER_UYG_ENUM_AD,
		DIGER_UYG_ID,
		COLUMN4,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		
	}	
}

#pragma warning restore 1591
