// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{


    [Dapper.Contrib.Extensions.Table("Pos.Uygulama")]

    public partial class T_Pos_Uygulama    {
		public T_Pos_Uygulama()
		{
		}

        //public static string SchemeName { get { return "Pos"; } }
        public static string GetSchema() { return "Pos"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        public string AD { get; set;}
        public string ACIKLAMA { get; set;}
        public string LOGO_URL { get; set;}
        [Required]
        public string UYGULAMA_KEY { get; set;}
        [Required]
        public string UYGULAMA_SIFRE { get; set;}
        [Required]
        public int ARACI_KURUM_KOD_ID { get; set;}
        [Required]
        public long ARACI_KURUM_API_CLIENT_ID { get; set;}
        [Required]
        public string ARACI_KURUM_API_KEY { get; set;}
        [Required]
        public string ARACI_KURUM_API_SIFRE { get; set;}

        [Required]
        public string ARACI_KURUM_STORE_KEY { get; set; }
        

        [Required]
        public bool IS_AKTIF { get; set;}
        [Required]
        public bool ISDELETED { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
        public string CREATEDIP { get; set;}
        public string MODIFIEDIP { get; set;}
    }
	
    
    public class T_Pos_UygulamaMapper : AutoClassMapper<T_Pos_Uygulama>
    {
        public T_Pos_UygulamaMapper()
            : base()
        {
            Schema("Pos");
        }
    }
 
	public enum T_Pos_Uygulama_Properties {

		ID,
		AD,
		ACIKLAMA,
		LOGO_URL,
		UYGULAMA_KEY,
		UYGULAMA_SIFRE,
		ARACI_KURUM_KOD_ID,
		ARACI_KURUM_API_CLIENT_ID,
		ARACI_KURUM_API_KEY,
		ARACI_KURUM_API_SIFRE,
		IS_AKTIF,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		CREATEDIP,
		MODIFIEDIP,
		
	}	
}

#pragma warning restore 1591
