// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{


    [Dapper.Contrib.Extensions.Table("Pos.Odeme")]

    public partial class T_Pos_Odeme    {
		public T_Pos_Odeme()
		{
		}

        //public static string SchemeName { get { return "Pos"; } }
        public static string GetSchema() { return "Pos"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        [Required]
        public string ODEME_KEY { get; set;}
        [Required]
        public int ODEME_SON_DURUM_KOD_ID { get; set;}

   
        public string ODEME_SON_DURUM_ACIKLAMA { get; set; }
        
        [Required]
        public DateTime KEY_OLUSTURULMA_TARIH { get; set;}
        [Required]
        public DateTime KEY_SON_KULLANIM_TARIH { get; set;}
        [Required]
        public int UYGULAMA_ID { get; set;}
        public string UYGULAMA_RETURN_URL { get; set;}
        public string UYGULAMA_CALL_GET_METOD { get; set; }
        
        public decimal? TUTAR { get; set;}
        public string ACIKLAMA { get; set;}
        public string CLIENT_ODEME_ID { get; set;}
        [Required]
        public int SECILEN_ODEME_YONTEM_KOD_ID { get; set;}
        [Required]
        public int SECILEN_ODEME_YONTEM_GUVENLIK_KOD_ID { get; set;}
        public DateTime? ODEME_ISLEM_TARIH { get; set;}
        [Required]
        public int ARACI_KURUM_KOD_ID { get; set;}
        [Required]
        public string ARACI_KURUM_ODEME_REFERANS_ID { get; set;}
        [Required]
        public int ODEME_KISI_BILGI_ID { get; set;}
        public string KREDI_KART_NO { get; set;}
        [Required]
        public bool ISDELETED { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
        public string CREATEDIP { get; set;}
        public string MODIFIEDIP { get; set;}
    }
	
    
    public class T_Pos_OdemeMapper : AutoClassMapper<T_Pos_Odeme>
    {
        public T_Pos_OdemeMapper()
            : base()
        {
            Schema("Pos");
        }
    }
 
	public enum T_Pos_Odeme_Properties {

		ID,
		ODEME_KEY,
		ODEME_SON_DURUM_KOD_ID,
		KEY_OLUSTURULMA_TARIH,
		KEY_SON_KULLANIM_TARIH,
		UYGULAMA_ID,
		UYGULAMA_RETURN_URL,
        UYGULAMA_CALL_GET_METOD,
        TUTAR,
		ACIKLAMA,
		CLIENT_ODEME_ID,
		SECILEN_ODEME_YONTEM_KOD_ID,
		SECILEN_ODEME_YONTEM_GUVENLIK_KOD_ID,
		ODEME_ISLEM_TARIH,
		ARACI_KURUM_KOD_ID,
		ARACI_KURUM_ODEME_REFERANS_ID,
		ODEME_KISI_BILGI_ID,
		KREDI_KART_NO,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		CREATEDIP,
		MODIFIEDIP,
		
	}	
}

#pragma warning restore 1591
