// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{


    [Dapper.Contrib.Extensions.Table("Pos.OdemeDurumHareket")]

    public partial class T_Pos_OdemeDurumHareket    {
		public T_Pos_OdemeDurumHareket()
		{
		}

        //public static string SchemeName { get { return "Pos"; } }
        public static string GetSchema() { return "Pos"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        [Required]
        public int ODEME_ID { get; set;}
        [Required]
        public string ODEME_KEY { get; set;}
        public int? ODEME_DURUM_KOD_ID { get; set;}
        [Required]
        public string ODEME_DURUM_ACIKLAMA { get; set;}
        [Required]
        public bool IS_SON_DURUM { get; set;}
        public DateTime? HAREKET_BASLANGIC_TARIH { get; set;}
        public DateTime? HAREKET_BITIS_TARIH { get; set;}
        [Required]
        public bool ISDELETED { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
        public string CREATEDIP { get; set;}
        public string MODIFIEDIP { get; set;}
    }
	
    
    public class T_Pos_OdemeDurumHareketMapper : AutoClassMapper<T_Pos_OdemeDurumHareket>
    {
        public T_Pos_OdemeDurumHareketMapper()
            : base()
        {
            Schema("Pos");
        }
    }
 
	public enum T_Pos_OdemeDurumHareket_Properties {

		ID,
		ODEME_ID,
		ODEME_KEY,
		ODEME_DURUM_KOD_ID,
		ODEME_DURUM_ACIKLAMA,
		IS_SON_DURUM,
		HAREKET_BASLANGIC_TARIH,
		HAREKET_BITIS_TARIH,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		CREATEDIP,
		MODIFIEDIP,
		
	}	
}

#pragma warning restore 1591
