// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{


    //[Dapper.Contrib.Extensions.Table("u1555990_borsav2.t_process_bilgi")] --ae değişiklik
	[Dapper.Contrib.Extensions.Table("t_process_bilgi")]

    //public partial class T_u1555990_borsav2_t_process_bilgi --ae değişiklik
	 public partial class t_process_bilgi    {
		//public T_u1555990_borsav2_t_process_bilgi()--ae değişiklik
		public t_process_bilgi()
		{
		}

        //public static string SchemeName { get { return "u1555990_borsav2"; } }
        public static string GetSchema() { return "u1555990_borsav2"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        [Required]
        public int PROCESS_ID { get; set;}
        public DateTime? BASLANGIC_TARIH { get; set;}
        public int? YONTEM_TIP_KOD_ID { get; set;}
        public string SYMBOL { get; set;}
        public decimal? FIYAT { get; set;}
        public decimal? DEGISIM { get; set;}
        [Required]
        public int KAC_SALISE_BIR_CALISSIN { get; set;}
        [Required]
        public int COUNT { get; set;}
        [Required]
        public int IS_ALIM_YAPILABILIR { get; set;}
        [Required]
        public int IS_GERCEK_ISLEM { get; set;}
        [Required]
        public int IS_SATIS_SONU_KAPAT { get; set;}
        [Required]
        public decimal BAKILACAK_EMIR_SAYISI { get; set;}
        [Required]
        public decimal HARCANACAK_TOPLAM_TUTAR { get; set;}
        [Required]
        public decimal ALICILAR_YUKSEKLIK_ORANI { get; set;}
        [Required]
        public decimal SATICILAR_YUKSEKLIK_ORANI { get; set;}
        [Required]
        public decimal HEDEF_FIYAT_BELIRLEME_ORANI { get; set;}
        [Required]
        public decimal STOP_LOST_BELIRLEME_ORANI { get; set;}
        [Required]
        public decimal HEDEF_FIYAT_GUNCELLEME_ORANI { get; set;}
        [Required]
        public decimal STOP_LOST_GUNCELLEME_ORANI { get; set;}
        [Required]
        public int IS_SATISTA_ALICI_YUKSEKLINE_BAK { get; set;}
        [Required]
        public decimal KAPANIS_FIYAT_TOLARANS_DEGERI { get; set;}
        [Required]
        public int PES_PESE_KIRMIZI_MUM_ADETI { get; set;}
        [Required]
        public decimal ALIM_ICIN_BEKLENECEK_FIYAT { get; set;}
        [Required]
        public int ALIM_ICIN_BEKLENECEK_DAKIKA { get; set;}
        [Required]
        public int ISDELETED { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
    }
	
    
   // public class T_u1555990_borsav2_t_process_bilgiMapper : AutoClassMapper<T_u1555990_borsav2_t_process_bilgi> --ae değişiklik
	public class t_process_bilgiMapper : AutoClassMapper<t_process_bilgi>
    {
        //public T_u1555990_borsav2_t_process_bilgiMapper() --ae değişiklik
		public t_process_bilgiMapper()
            : base()
        {
            Schema("u1555990_borsav2");
        }
    }
 
	//public enum T_u1555990_borsav2_t_process_bilgi_Properties {--ae değişiklik
	public enum t_process_bilgi_Properties {

		ID,
		PROCESS_ID,
		BASLANGIC_TARIH,
		YONTEM_TIP_KOD_ID,
		SYMBOL,
		FIYAT,
		DEGISIM,
		KAC_SALISE_BIR_CALISSIN,
		COUNT,
		IS_ALIM_YAPILABILIR,
		IS_GERCEK_ISLEM,
		IS_SATIS_SONU_KAPAT,
		BAKILACAK_EMIR_SAYISI,
		HARCANACAK_TOPLAM_TUTAR,
		ALICILAR_YUKSEKLIK_ORANI,
		SATICILAR_YUKSEKLIK_ORANI,
		HEDEF_FIYAT_BELIRLEME_ORANI,
		STOP_LOST_BELIRLEME_ORANI,
		HEDEF_FIYAT_GUNCELLEME_ORANI,
		STOP_LOST_GUNCELLEME_ORANI,
		IS_SATISTA_ALICI_YUKSEKLINE_BAK,
		KAPANIS_FIYAT_TOLARANS_DEGERI,
		PES_PESE_KIRMIZI_MUM_ADETI,
		ALIM_ICIN_BEKLENECEK_FIYAT,
		ALIM_ICIN_BEKLENECEK_DAKIKA,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		
	}	
}

#pragma warning restore 1591
