// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{


    //[Dapper.Contrib.Extensions.Table("u1555990_borsav2.t_telegram_kullanici")] --ae değişiklik
	[Dapper.Contrib.Extensions.Table("t_telegram_kullanici")]

    //public partial class T_u1555990_borsav2_t_telegram_kullanici --ae değişiklik
	 public partial class t_telegram_kullanici    {
		//public T_u1555990_borsav2_t_telegram_kullanici()--ae değişiklik
		public t_telegram_kullanici()
		{
		}

        //public static string SchemeName { get { return "u1555990_borsav2"; } }
        public static string GetSchema() { return "u1555990_borsav2"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        [Required]
        public long TELEGRAM_ID { get; set;}
        [Required]
        public string TELEGRAM_BOT_TOKEN { get; set;}
        [Required]
        public string AD_SOYAD { get; set;}
        [Required]
        public int IS_YONETICI { get; set;}
        [Required]
        public int IS_KABUL_EDILDI { get; set;}
        public DateTime? IZIN_EXP_TARIH { get; set;}
        public string COLUMN2 { get; set;}
        public string COLUMN3 { get; set;}
        public string COLUMN4 { get; set;}
        [Required]
        public int ISDELETED { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
    }
	
    
   // public class T_u1555990_borsav2_t_telegram_kullaniciMapper : AutoClassMapper<T_u1555990_borsav2_t_telegram_kullanici> --ae değişiklik
	public class t_telegram_kullaniciMapper : AutoClassMapper<t_telegram_kullanici>
    {
        //public T_u1555990_borsav2_t_telegram_kullaniciMapper() --ae değişiklik
		public t_telegram_kullaniciMapper()
            : base()
        {
            Schema("u1555990_borsav2");
        }
    }
 
	//public enum T_u1555990_borsav2_t_telegram_kullanici_Properties {--ae değişiklik
	public enum t_telegram_kullanici_Properties {

		ID,
		TELEGRAM_ID,
		TELEGRAM_BOT_TOKEN,
		AD_SOYAD,
		IS_YONETICI,
		IS_KABUL_EDILDI,
		IZIN_EXP_TARIH,
		COLUMN2,
		COLUMN3,
		COLUMN4,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		
	}	
}

#pragma warning restore 1591
