// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DapperExtensions.Mapper;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prj.DAL.Model
{


    //[Dapper.Contrib.Extensions.Table("u1555990_borsav2.t_user_binance_bilgi")] --ae değişiklik
	[Dapper.Contrib.Extensions.Table("t_user_binance_bilgi")]

    //public partial class T_u1555990_borsav2_t_user_binance_bilgi --ae değişiklik
	 public partial class t_user_binance_bilgi    {
		//public T_u1555990_borsav2_t_user_binance_bilgi()--ae değişiklik
		public t_user_binance_bilgi()
		{
		}

        //public static string SchemeName { get { return "u1555990_borsav2"; } }
        public static string GetSchema() { return "u1555990_borsav2"; }

        //[AutoIncrement]
		[Dapper.Contrib.Extensions.Key]
        public int ID { get; set;}
        [Required]
        public int USER_ID { get; set;}
        public string API_KEY { get; set;}
        public string SECRET_KEY { get; set;}
        public string ACIKLAMA { get; set;}
        [Required]
        public int ISDELETED { get; set;}
        public long? CREATEDUSER { get; set;}
        public DateTime? CREATEDDATE { get; set;}
        public long? MODIFIEDUSER { get; set;}
        public DateTime? MODIFIEDDATE { get; set;}
    }
	
    
   // public class T_u1555990_borsav2_t_user_binance_bilgiMapper : AutoClassMapper<T_u1555990_borsav2_t_user_binance_bilgi> --ae değişiklik
	public class t_user_binance_bilgiMapper : AutoClassMapper<t_user_binance_bilgi>
    {
        //public T_u1555990_borsav2_t_user_binance_bilgiMapper() --ae değişiklik
		public t_user_binance_bilgiMapper()
            : base()
        {
            Schema("u1555990_borsav2");
        }
    }
 
	//public enum T_u1555990_borsav2_t_user_binance_bilgi_Properties {--ae değişiklik
	public enum t_user_binance_bilgi_Properties {

		ID,
		USER_ID,
		API_KEY,
		SECRET_KEY,
		ACIKLAMA,
		ISDELETED,
		CREATEDUSER,
		CREATEDDATE,
		MODIFIEDUSER,
		MODIFIEDDATE,
		
	}	
}

#pragma warning restore 1591
